# Generated by Django 5.0.2 on 2024-03-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('is_home', models.BooleanField()),
                ('slug', models.SlugField(blank=True, default='', editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
            ],
        ),
    ]
