# Generated by Django 5.0.3 on 2024-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blog_category_blog_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="categories",
            field=models.ManyToManyField(blank=True, to="blog.category"),
        ),
    ]
