# Generated by Django 5.0.3 on 2024-06-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("experience_years", models.PositiveIntegerField()),
                ("happy_customers", models.PositiveIntegerField()),
                ("projects_finished", models.PositiveIntegerField()),
                ("digital_awards", models.PositiveIntegerField()),
            ],
        ),
    ]
